quiz = [
  { quest: '1. Quanto tempo a Luz do Sol leva para chegar à Terra?', res: {1: '8 minutos', 2: '19 minutos', 3: '2 minutos', 4: '5 minutos'} },
  { quest: '2. Qual a velocidade da Luz?', res: {1: '300 mil km/s', 2: '300 mil km/h', 3: '298 mil km/h', 4: '298 mil km/s'} },
  { quest: '3. Qual destes pode chover diamante?', res: {1: 'Urano', 2: 'Marte', 3: 'Vênus', 4: 'Mercúrio'} },
  { quest: '4. Quem propôs a existência dos Buracos Negros?', res: {1: 'Karl Schwarzschild', 2: 'Albert Einstein', 3: 'Karl Marx', 4: 'Stephen Hawkins'} },
  { quest: '5. Qual planeta do Sistema Solar tem massa equivalente a 317 vezes a massa da Terra?', res: {1: 'Júpiter', 2: 'Urano', 3: 'Saturno', 4: 'Netuno'} },
  { quest: '6. A Lua está distante da Terra, em média...', res: {1: '1.282 segundos-luz', 2: '2.252 segundos-luz', 3: '1.381 segundos-luz', 4: '11.282 segundos-luz'} },
  { quest: '7. A Lua se afasta da Terra, em média...', res: {1: '3 metros por século', 2: '5 metros por ano', 3: '6 centímetros por ano', 4: '12 centímetros por século'} },
  { quest: '8. Qual o sexto planeta do Sistema Solar?', res: {1: 'Saturno', 2: 'Marte', 3: 'Urano', 4: 'Júpiter'} },
  { quest: '9. O planeta mais quente do sistema solar é...', res: {1: 'Vênus', 2: 'Mercúrio', 3: 'Marte', 4: 'Netuno'} },
  { quest: '10. Os especialistas acreditam que a Via Láctea dá origem a...', res: {1: '7 novas estrelas por ano', 2: '2 estrelas por mês', 3: '14 estrelas por década', 4: '5 estrelas por ano'} },
  { quest: '11. O que está localizado no centro da nossa galáxia?', res: {1: 'Buraco Negro', 2: 'Nada', 3: 'Um enorme planeta', 4: 'Várias estrelas'} },
  { quest: '12. Quem propôs a teoria que hoje conhecemos como Big Bang?', res: {1: 'Georges Lemaître', 2: 'Albert Einstein', 3: 'Stephen Hawkins', 4: 'Edwin Hubble'} },
  { quest: '13. Qual o menor planeta do sistema solar?', res: {1: 'Mercúrio', 2: 'Terra', 3: 'Plutão', 4: 'Marte'} },
  { quest: '14. Qual a cor da estrela do Sistema Solar?', res: {1: 'Branco', 2: 'Amarelo', 3: 'Verde', 4: 'Laranja'} },
  { quest: '15. Estima-se que este objeto foi o primeiro a sair do Sistema Solar.', res: {1: 'Voyager 1', 2: 'Sputnik', 3: 'Luna 10', 4: 'Galileo'} },
]

quizGeo = [
  {quest:'1. Grécia é um país do continente', res: {1: 'Europeu', 2: 'Africano', 3: 'Asiático', 4: 'Oceânico'}},
  {quest:'2. O Brasil localiza-se em...', res: {1: 'América do Sul', 2: 'América do Norte', 3: 'América Central', 4: 'África'}},
  {quest:'3. Capital da Espanha é...', res: {1: 'Madrid', 2: 'Barcelona', 3: 'Salamanca', 4: 'Valência'}},
  {quest:'4. Onde localiza-se o Egito?', res: {1: 'África', 2: 'Grécia', 3: 'Oriente Médio', 4: 'Sul do Oriente Médio'}},
  {quest:'5. Qual destes países não faz parte do Oriente Médio?', res: {1: 'Nepal', 2: 'Omã', 3: 'Bahrain', 4: 'Turquia'}},
  {quest:'6. Um destes é do Reino Unido...', res: {1: 'País de Gales', 2: 'Suécia', 3: 'Noruega', 4: 'Islândia'}},
  {quest:'7. Este faz fronteira com o Sul do Brasil', res: {1: 'Uruguai', 2: 'Paraguai', 3: 'Suriname', 4: 'Guiana Francesa'}},
  {quest:'8. Continente de Madagascar', res: {1: 'África', 2: 'Europa', 3: 'Ásia', 4: 'Leste da Ásia'}},
  {quest:'9. O Oceano que banha o Brasil', res: {1: 'Oceano Atlântico', 2: 'Oceano Pacífico', 3: 'Oceano Índico', 4: 'Oceano Ártico'}},
  {quest:'10. E o Oceano que banha o Chile?', res: {1: 'Oceano Pacífico', 2: 'Oceano Atlântico', 3: 'Oceano Atlântico Sul', 4: 'Oceano Pacífico Norte'}},
  {quest:'11. Chernobyl e Pripyat localizam-se no país', res: {1: 'Ucrânia', 2: 'Bielorrússia', 3: 'Rússia', 4: 'Polônia'}},
  {quest:'12. O maior continente do mundo', res: {1: 'Ásia', 2: 'América', 3: 'África', 4: 'Antártida'}},
  {quest:'13. Qual a capital dos EUA?', res: {1: 'Washington, D.C.', 2: 'Chicago', 3: 'Nova York', 4: 'Pierre'}},
  {quest:'14. Capital do Canadá é...', res: {1: 'Ottawa', 2: 'Toronto', 3: 'Vancouver', 4: 'Kingston'}},
  {quest:'15. Iraque localiza-se em qual continente?', res: {1: 'Ásia', 2: 'África', 3: 'Oriente Médio', 4: 'Europa'}},
]

quizHistG = [
  { quest: '1. O faraó foi um grande símbolo do Egito Antigo. Mas você sabe quem foi o primeiro?', res: {1: 'Narmer', 2: 'Tutmés III', 3: 'Ramsés II', 4: 'Tutancâmon'} },
  { quest: '2. Agora que você sabe quem foi o primeiro faraó, me diga qual foi o último destes.', res: {1: 'Cesarião', 2: 'Cleópatra', 3: 'Ramsés II', 4: 'Quéops'} },
  { quest: '3. Deixando o faraó de lado, qual destes deuses foi o responsável pela criação do mundo na mitologia egipcía?', res: {1: 'Rá', 2: 'Osíris', 3: 'Hórus', 4: 'Anúbis'} },
  { quest: '4. A maior Pirâmide já encontrada no Egito data dos anos...', res: {1: '2.560 a.C.', 2: '2.900 a.C.', 3: '3.065 a.C.', 4: '1.548 a.C.'} },
  { quest: '5. A maior Pirâmide foi criada com intuíto de ser o túmulo de...', res: {1: 'Queops', 2: 'Nilo', 3: 'Narmer', 4: 'Ramsés'} },
  { quest: '6. Saindo do Egito, temos a Grécia Antiga, a qual se formou com a miscigenação dos povos...', res: {1: 'Arianos', 2: 'Romanos', 3: 'Egipcíos', 4: 'Troia'} },
  { quest: '7. Dentro da história da Grécia, temos o seu Período Arcaico, que foi entre os anos...', res: {1: '800 a.C. e 500 a.C.', 2: '1.200 a.C. e 900 a.C.', 3: '870 a.C. e 100 d.C.', 4: '200 d.C. e 450 d.C.'} },
  { quest: '8. E o Período Arcaico corresponde ao', res: {1: 'Terceiro Período', 2: 'Segundo Período', 3: 'Primeiro Período', 4: 'Último Período'} },
  { quest: '9. Quem estava envolvido na Guerra do Peloponeso?', res: {1: 'Atenas e Esparta', 2: 'Gregos e Aquemênida', 3: 'Grécia e Troia', 4: 'Esparta e Tebas'} },
  { quest: '10. E quem estava batalhando nas Guerras Médicas?', res: {1: 'Gregos e Aquemênida', 2: 'Grécia e Troia', 3: 'Tebas e Troia', 4: 'Atenas e Troia'} },
  { quest: '11. Mudando para a Peste Negra, a pandemia mais devastadora da história. Em que período ocorreu?', res: {1: '1.346 - 1.353', 2: '1.233 - 1.245', 3: '1.617 - 1.624', 4: '1.689 - 1.717'} },
  { quest: '12. Estima-se que a doença da Peste Negra surgiu na...', res: {1: 'China', 2: 'Itália', 3: 'França', 4: 'Mongólia'} },
  { quest: '13. Pulando no tempo, a Primeira Guerra Mundial teve seu início no dia...', res: {1: '28, jul., 1914', 2: '19, Mar., 1914', 3: '22, dez., 1914', 4: '18, abr., 1914'} },
  { quest: '14. E teve seu fim no dia...', res: {1: '11, nov., 1918', 2: '15, dez., 1918', 3: '21, nov., 1918', 4: '28, set., 1918'} },
  { quest: '15. Já a Segunda Guerra Mundial teve seu início no dia...', res: {1: '1, set., 1939', 2: '3, abr., 1939', 3: '9, jun., 1939', 4: '12, out., 1939'} },
]

quizConG = [
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
  { quest: '', res: {1: '', 2: '', 3: '', 4: ''} },
]
