quiz = [
  { quest: '1. Quanto tempo a Luz do Sol leva para chegar à Terra?', res: {1: '8 minutos', 2: '19 minutos', 3: '2 minutos', 4: '5 minutos'} },
  { quest: '2. Qual a velocidade da Luz?', res: {1: '300 mil km/s', 2: '300 mil km/h', 3: '298 mil km/h', 4: '298 mil km/s'} },
  { quest: '3. Qual destes pode chover diamante?', res: {1: 'Urano', 2: 'Marte', 3: 'Vênus', 4: 'Mercúrio'} },
  { quest: '4. Quem propôs a existência dos Buracos Negros?', res: {1: 'Karl Schwarzschild', 2: 'Albert Einstein', 3: 'Karl Marx', 4: 'Stephen Hawkins'} },
  { quest: '5. Qual planeta do Sistema Solar tem massa equivalente a 317 vezes a massa da Terra?', res: {1: 'Júpiter', 2: 'Urano', 3: 'Saturno', 4: 'Netuno'} },
  { quest: '6. A Lua está distante da Terra, em média...', res: {1: '1.282 segundos-luz', 2: '2.252 segundos-luz', 3: '1.381 segundos-luz', 4: '11.282 segundos-luz'} },
  { quest: '7. A Lua se afasta da Terra, em média...', res: {1: '3 metros por século', 2: '5 metros por ano', 3: '6 centímetros por ano', 4: '12 centímetros por século'} },
  { quest: '8. Qual o sexto planeta do Sistema Solar?', res: {1: 'Saturno', 2: 'Marte', 3: 'Urano', 4: 'Júpiter'} },
  { quest: '9. O planeta mais quente do sistema solar é...', res: {1: 'Vênus', 2: 'Mercúrio', 3: 'Marte', 4: 'Netuno'} },
  { quest: '10. Os especialistas acreditam que a Via Láctea dá origem a...', res: {1: '7 novas estrelas por ano', 2: '2 estrelas por mês', 3: '14 estrelas por década', 4: '5 estrelas por ano'} },
  { quest: '11. O que está localizado no centro da nossa galáxia?', res: {1: 'Buraco Negro', 2: 'Nada', 3: 'Um enorme planeta', 4: 'Várias estrelas'} },
  { quest: '12. Quem propôs a teoria que hoje conhecemos como Big Bang?', res: {1: 'Georges Lemaître', 2: 'Albert Einstein', 3: 'Stephen Hawkins', 4: 'Edwin Hubble'} },
  { quest: '13. Qual o menor planeta do sistema solar?', res: {1: 'Mercúrio', 2: 'Terra', 3: 'Plutão', 4: 'Marte'} },
  { quest: '14. Qual a cor da estrela do Sistema Solar?', res: {1: 'Branco', 2: 'Amarelo', 3: 'Verde', 4: 'Laranja'} },
  { quest: '15. Estima-se que este objeto foi o primeiro a sair do Sistema Solar.', res: {1: 'Voyager 1', 2: 'Sputnik', 3: 'Luna 10', 4: 'Galileo'} },
]

quizGeo = [
  {quest:'Grécia é um país do continente', res: {1: 'Europeu', 2: 'Africano', 3: 'Asiático', 4: 'Oceânico'}},
  {quest:'O Brasil localiza-se em...', res: {1: 'América do Sul', 2: 'América do Norte', 3: 'América Central', 4: 'África'}},
  {quest:'Capital da Espanha é...', res: {1: 'Madrid', 2: 'Barcelona', 3: 'Salamanca', 4: 'Valência'}},
  {quest:'Onde localiza-se o Egito?', res: {1: 'África', 2: 'Grécia', 3: 'Oriente Médio', 4: 'Sul do Oriente Médio'}},
  {quest:'Qual destes países não faz parte do Oriente Médio?', res: {1: 'Nepal', 2: 'Omã', 3: 'Bahrain', 4: 'Turquia'}},
  {quest:'Um destes é do Reino Unido...', res: {1: 'País de Gales', 2: 'Suécia', 3: 'Noruega', 4: 'Islândia'}},
  {quest:'Este faz fronteira com o Sul do Brasil', res: {1: 'Uruguai', 2: 'Paraguai', 3: 'Suriname', 4: 'Guiana Francesa'}},
  {quest:'Continente de Madagascar', res: {1: 'África', 2: 'Europa', 3: 'Ásia', 4: 'Leste da Ásia'}},
  {quest:'O Oceano que banha o Brasil', res: {1: 'Oceano Atlântico', 2: 'Oceano Pacífico', 3: 'Oceano Índico', 4: 'Oceano Ártico'}},
  {quest:'E o Oceano que banha o Chile?', res: {1: 'Oceano Pacífico', 2: 'Oceano Atlântico', 3: 'Oceano Atlântico Sul', 4: 'Oceano Pacífico Norte'}},
  {quest:'Chernobyl e Pripyat localizam-se no país', res: {1: 'Ucrânia', 2: 'Bielorrússia', 3: 'Rússia', 4: 'Polônia'}},
  {quest:'O maior continente do mundo', res: {1: 'Ásia', 2: 'América', 3: 'África', 4: 'Antártida'}},
  {quest:'Qual a capital dos EUA?', res: {1: 'Washington, D.C.', 2: 'Chicago', 3: 'Nova York', 4: 'Pierre'}},
  {quest:'Capital do Canadá é...', res: {1: 'Ottawa', 2: 'Toronto', 3: 'Vancouver', 4: 'Kingston'}},
  {quest:'Iraque localiza-se em qual continente?', res: {1: 'Ásia', 2: 'África', 3: 'Oriente Médio', 4: 'Europa'}},
]
